### ISSUE TITLE
Questions on the training mode

### ISSUE THREAD

**Issue by ronjonxu** [megvii-research/DVN#1]
Dear author,

Could you tell me the difference between the training mode 'Recons' and the training mode 'Fusion'? Which mode should be used first? Thank you

**Comment by ronjonxu** [comment]
By the way, why do you change the brightness of test image by simply * 5 and divide the mean value of pixels of the green?
https://github.com/megvii-research/DVN/blob/58735ac57472cf53d8af291456867f134e53db33/dataset.py#L138

**Comment by MatteoPony** [comment]
Dear ronjonxu,

Did you have run this code? I have some problem on env setting...
When I install the requirement package, the refile latest version is 0.4.1, so I can't run this code, please give me some help, thank you!
